version: 0.1

phases:
  install:
    commands:
      - printenv
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mkdir -p build
      - echo tar jcf build/myApp-$(date +%Y%m%d%H%m%S).tar.bz2 .eslintrc.js .gitignore README.md buildspec.yml package.json serverless.yml src test
      - echo npm install -g serverless
      - echo serverless -v -s $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2 | cut -d'_' -f3) deploy

artifacts:
  files:
    - build*/**
  discard-paths: yes